#!/bin/bash

# 获取系统信息
HOSTNAME=$(hostname)
KERNEL=$(uname -r)
UPTIME=$(uptime -p)
LOAD=$(cat /proc/loadavg | awk '{print $1 " " $2 " " $3}')
MEMORY=$(free -h | awk '/^Mem:/ {print $3 "/" $2}')

# 获取磁盘信息
DISKS=$(df -h | awk '/^\/dev\// {printf "%-20s %s\n", $1, $3 "/" $2}')

# 获取IP地址和接口名称
INTERFACES=$(ip -o addr show | awk '$3 == "inet" {printf "%-20s %s\n", $2 , $4}')

# 获取温度信息
# TEMPERATURES=$(sensors | awk '/^.*_thermal-virtual-0/ {print $1; getline; getline; print $2}')
TEMPERATURES=$(cat /sys/devices/virtual/thermal/thermal_zone*/temp | awk '{printf "%-30s %.2f°C\n", "CPU Temperature:", $1/1000}')

# 设置颜色和格式化
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 显示系统信息
echo -e "${GREEN}------------------------------------------------------------${NC}"
echo -e "${GREEN} Welcome to ${HOSTNAME}!${NC}"
echo -e "${GREEN}------------------------------------------------------------${NC}"
echo -e "${YELLOW} Kernel:${NC} ${BLUE}${KERNEL}${NC}"
echo -e "${YELLOW} Uptime:${NC} ${BLUE}${UPTIME}${NC}"
echo -e "${YELLOW} Load:${NC} ${BLUE}${LOAD}${NC}"
echo -e "${YELLOW} Memory:${NC} ${BLUE}${MEMORY}${NC}"
echo -e "${YELLOW} Disks:${NC}"
echo -e "${BLUE}${DISKS}${NC}"
echo -e "${YELLOW} IP Addresses:${NC}"
echo -e "${BLUE}${INTERFACES}${NC}"
echo -e "${YELLOW} Temperatures:${NC}"
if [[ -n "$TEMPERATURES" ]]; then
    echo -e "${BLUE}${TEMPERATURES}${NC}"
else
    echo -e "${BLUE}No temperature information available.${NC}"
fi
echo -e "${GREEN}------------------------------------------------------------${NC}"
