---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- OneCloud:
    - aria2:
        icon: https://pic2.zhimg.com/v2-9c7e25d52582980ce8a03a69c2e17db5_1440w.jpg?source=172ae18b
        href: http://192.168.124.14:16880/
        description: 下载工具
        server: OneCloud
        container: aria2-aria2-1
    - casaOS:
        ping: 192.168.124.14
        icon: https://ts1.cn.mm.bing.net/th?id=ODLS.bcccf52e-76a4-41da-a7a2-fb1881350703&w=32&h=32&qlt=91&pcl=fffffa&o=6&pid=1.2
        href: http://192.168.124.14
        description: 管理工具
    - Portainer:
        server: OneCloud
        container: portainer
        icon: portainer.png
        href: "http://192.168.124.14:9000/"
        description: 容器管理服务器
        widget:
            type: portainer
            url: http://192.168.124.14:9000
            env: 2
            key: ptr_/WFI4DVzzDX1h8/WUX/qcKqFX5orH7GmimVmutK0QdY=
    - kodbox:
        icon: https://ts1.cn.mm.bing.net/th?id=ODLS.4ea4e788-5329-4b17-b95c-d2a0f46452ee&w=32&h=32&qlt=90&pcl=fffffa&o=6&pid=1.2
        href: http://192.168.124.14:8098
        server: OneCloud
        container: kodbox-kodbox-1
    - navidrome:
        icon: https://ts3.cn.mm.bing.net/th?id=ODLS.5326a48a-7ae4-4c15-8a4a-3fde0d298155&w=32&h=32&qlt=91&pcl=fffffa&o=6&pid=1.2
        href: http://192.168.124.14:4533
        server: OneCloud
        container: navidrome
        widget:
            type: navidrome
            url: http://192.168.124.14:4533
            user: wood
            token: b1e4999163950f96fa7ef59b1f0f570b
            salt: salt
    - HomePage:
        server: OneCloud
        icon: https://ts1.cn.mm.bing.net/th?id=ODLS.A2450BEC-5595-40BA-9F13-D9EC6AB74B9F&w=32&h=32&qlt=91&pcl=fffffa&o=6&pid=1.2
        container: homepage

- J3060:
    - Aria2:
        href: http://192.168.124.101/ariang
        description: 下载工具
        icon: https://pic2.zhimg.com/v2-9c7e25d52582980ce8a03a69c2e17db5_1440w.jpg?source=172ae18b
    - 管理页面:
        icon: https://ts4.cn.mm.bing.net/th?id=ODLS.abb46ae2-fdd4-4abc-a665-5e4ae0b8e98f&w=32&h=32&qlt=90&pcl=fffffa&o=6&pid=1.2
        href: http://192.168.124.101/
        description: iStoreOS管理页面
        ping: 192.168.124.101
    - VSCode Server:
        icon: https://ts4.cn.mm.bing.net/th?id=ODLS.2d8f99b9-7bcb-4f0f-be03-922d3eb10c83&w=32&h=32&qlt=95&pcl=fffffa&o=6&pid=1.2
        server: iStoreOS
        container: codeserver
        href: http://192.168.124.101:8085/
        description: 代码编写
    - OneCloud:
        icon: https://ts2.cn.mm.bing.net/th?id=ODLS.cf634298-1a0f-44eb-b32b-0b416fb83914&w=32&h=32&qlt=90&pcl=fffffa&o=6&pid=1.2
        server: iStoreOS
        container: OneCloud
    - HomePage:
        icon: https://ts1.cn.mm.bing.net/th?id=ODLS.A2450BEC-5595-40BA-9F13-D9EC6AB74B9F&w=32&h=32&qlt=91&pcl=fffffa&o=6&pid=1.2
        server: iStoreOS
        container: HomePage
    - Portainer:
        description: 容器情况
        icon: portainer.png
        widget:
            type: portainer
            url: http://192.168.124.14:9000
            env: 4
            key: ptr_/WFI4DVzzDX1h8/WUX/qcKqFX5orH7GmimVmutK0QdY=
- D410c:
    - kodbox:
        ping: 11.11.11.3
        href: http://11.11.11.3/
        icon: https://ts1.cn.mm.bing.net/th?id=ODLS.4ea4e788-5329-4b17-b95c-d2a0f46452ee&w=32&h=32&qlt=90&pcl=fffffa&o=6&pid=1.2
        description: 文档管理
    - aria2:
        ping: 11.11.11.3
        icon: https://pic2.zhimg.com/v2-9c7e25d52582980ce8a03a69c2e17db5_1440w.jpg?source=172ae18b
        href: http://11.11.11.3/aria2
        description: 下载服务
