---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- OneCloud:
    - casaOS:
        ping: 192.168.124.14
        icon: https://ts1.cn.mm.bing.net/th?id=ODLS.bcccf52e-76a4-41da-a7a2-fb1881350703&w=32&h=32&qlt=91&pcl=fffffa&o=6&pid=1.2
        href: http://192.168.124.14
        description: 管理工具
    - Portainer:
        server: iStoreOS
        container: portainer
        icon: portainer.png
        href: "http://192.168.124.101:9000/"
        description: 容器管理服务器
        widget:
            type: portainer
            url: http://192.168.124.101:9000
            env: 2
            key: ptr_9LkWwhvGlhKqEn4pewQSbHAiOpNV9Pqm9J0cA45RsFs=
    - qBittorrent:
        icon: qbittorrent.png
        description: pt下载
        href: http://192.168.124.14:8080
        ping: http://192.168.124.14:8080
        widget:
            type: qbittorrent
            url: http://192.168.124.14:8080
            username: admin
            password: 1QAZ2wsx.
    - transmission:
        icon: transmission.png
        description: pt上传
        href: http://192.168.124.14:9091
        ping: http://192.168.124.14:9091
        widget:
            type: transmission
            url: http://192.168.124.14:9091
            username: 1
            password: 1
            rpcUrl: /transmission/
    - HomePage:
        description: 页面导航
        server: OneCloud
        icon: homepage.png
        container: homepage
    - kodbox:
        description: 文档管理
        icon: https://ts1.cn.mm.bing.net/th?id=ODLS.4ea4e788-5329-4b17-b95c-d2a0f46452ee&w=32&h=32&qlt=90&pcl=fffffa&o=6&pid=1.2
        href: http://192.168.124.14:8098
        server: OneCloud
        container: kodbox-kodbox-1
    - OpenWRT:
        description: 软路由
        server: OneCloud
        icon: openwrt.png
        container: OpenWRT
    - navidrome:
        description: 音乐播放
        icon: navidrome.png
        href: http://192.168.124.14:4533
        server: OneCloud
        container: navidrome
        widget:
            type: navidrome
            url: http://192.168.124.14:4533
            user: wood
            token: b1e4999163950f96fa7ef59b1f0f570b
    - aria2:
        icon: ariang.png
        href: http://192.168.124.14:16880/
        description: 下载工具
        server: OneCloud
        container: aria2-aria2-1
- J3060:
    - iStoreOS:
        icon: openwrt.png
        href: http://192.168.124.101/
        description: iStoreOS管理页面
        ping: 192.168.124.101
    - Portainer:
        description: 容器情况
        icon: portainer.png
        widget:
            type: portainer
            url: http://192.168.124.14:9000
            env: 4
            key: ptr_/WFI4DVzzDX1h8/WUX/qcKqFX5orH7GmimVmutK0QdY=
    - qBittorrent:
        icon: qbittorrent.png
        description: pt下载
        href: http://192.168.124.101:8080
        ping: http://192.168.124.101:8080
        widget:
            type: qbittorrent
            url: http://192.168.124.101:8080
    - Aria2:
        href: http://192.168.124.101/ariang
        description: 下载工具
        icon: ariang.png
    - VSCode-Server:
        icon: vscode.png
        server: iStoreOS
        container: codeserver
        href: http://192.168.124.101:8085/
        description: 代码编写
    - OneThing:
        description: 网心云
        icon: https://ts2.cn.mm.bing.net/th?id=ODLS.cf634298-1a0f-44eb-b32b-0b416fb83914&w=32&h=32&qlt=90&pcl=fffffa&o=6&pid=1.2
        server: iStoreOS
        container: OneCloud
    - HomePage:
        description: 页面导航
        icon: homepage.png
        server: iStoreOS
        container: HomePage
# - D410c:
#     - kodbox:
#         ping: 11.11.11.3
#         href: http://11.11.11.3/
#         icon: https://ts1.cn.mm.bing.net/th?id=ODLS.4ea4e788-5329-4b17-b95c-d2a0f46452ee&w=32&h=32&qlt=90&pcl=fffffa&o=6&pid=1.2
#         description: 文档管理
#     - aria2:
#         ping: 11.11.11.3
#         icon: ariang.png
#         href: http://11.11.11.3/aria2
#         description: 下载工具
