---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- OneCloud:
    - aria2ng:
        icon: aria2.png
        href: http://192.168.124.14:16880/
        description: 下载工具
        server: OneCloud
        container: aria2-aria2-1
    - casaOS:
        href: http://192.168.124.14
        description: 管理工具
    - Portainer:
        server: OneCloud
        container: portainer
        icon: portainer.png
        href: "http://192.168.124.14:9000/"
        description: 容器管理服务器
        widget:
            type: portainer
            url: http://192.168.124.14:9000
            env: 2
            key: ptr_/WFI4DVzzDX1h8/WUX/qcKqFX5orH7GmimVmutK0QdY=
    - kodbox:
        href: http://192.168.124.14:8098
        server: OneCloud
        container: kodbox-kodbox-1
    - navidrome:
        href: http://192.168.124.14:4533
        server: OneCloud
        container: navidrome

- J3060:
    - 管理页面:
        href: http://192.168.124.101/
        description: iStoreOS管理页面
    - VSCode Server:
        server: StoreOS
        container: codeserver
        href: http://192.168.124.101:8085/
        description: 代码编写
    - OneCloud:
        server: StoreOS
        container: OneCloud
    - HomePage:
        server: StoreOS
        container: HomePage
	
- D410c:
    - kodbox:
        href: http://11.11.11.3/
        description: 文档管理
    - aria2:
        href: http://11.11.11.3/aria2
        description: 下载服务
