---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: true
    memory: true
    disk: /
- datetime:
    text_size: xl
    format:
      timeStyle: short
      hour12: false

    
- weatherapi:
     label: 北京
     latitude: 39.979958
     longitude: 116.382408
     units: metric  #imperial 
     apiKey: 389f9f027cfc41298c9112212232112
     cache: 60

- search:
    provider: bing
    target: _blank